var tableauQuestion = [
    {   question : "/report DI GUNAKAN KETIKA? ",
        propositionA : "Membutuhkan dana di kota",
        propositionB : "Minta di hidupin saat perang ",
        propositionC : "Untuk meminta Bantuan di saat bug",
        propositionD : "Melaporkan  hal yang tidak penting",
        reponse : "C"},
    {   question : "HAL PENTING APA YANG HARUS DI LAKUKAN PADA SETIAP WARGA?",
        propositionA : "Menghargai sesama player",
        propositionB : "Mengumpulkan uang sebanyak banyaknya",
        propositionC : "Perang setiap saat",
        propositionD : "Merampok untuk mendapatkan uang",
        reponse : "A"},
    {   question : "Apa hal yang dilakukan anda menjadi warga baru di kota SecretSociety.ID?",
        propositionA : "Rusuh/memukul warga lain",
        propositionB : "Berbicara kasar ke warga lain",
        propositionC : "Langsung ikut perang, walaupun belum kenal secara IC",
        propositionD : "Pergi ke JOB center,untuk memilih pekerjaan",
        reponse : "D"},
    {   question : "APA ITU VDM? ",
        propositionA : "Vehicle Dumb Machine",
        propositionB : "Mengendarai mobilnya sesuai aturan yang berlaku",
        propositionC : "Vehicle Death Match, atau dengan sengaja menabrak kendaraan warga lain dengan alasan yang tidak jelas",
        propositionD : "Variasi Dan Modifikasi",
        reponse : "C"},
    {   question : "APA ITU RDM?",
        propositionA : "Random Death match, membunuh orang dengan sengaja tanpa landasar RP berjalan",
        propositionB : "Relax Dan Menonton",
        propositionC : "Relokasi Dana Modal",
        propositionD : "Kegiatan yang menyenangkan",
        reponse : "A"},
    {   question : "APAKAH SIM WAJIB DIPERLUKAN OLEH SETIAP WARGA?",
        propositionA : "Tidak Perlu Karena Saya sudah Jago Menyetir",
        propositionB : "Gak Perlu Pak , saya hapal jalan tikus",
        propositionC : "tenang aja pak saya anak pejabat",
        propositionD : "SIM wajib dimiliki oleh setiap warga",
        reponse : "D"},
    {   question : "APA ITU MIXING? ",
        propositionA : "Mencampurkan bahan makanan menjadi satu",
        propositionB : "Mengaduk semen pak",
        propositionC : "Mencampurkan informasi yang didapat dari luar(ooc) ke dalam(ic) ",
        propositionD : "proses mengolah suatu produk",
        reponse : "C"},
    {   question : "APAKAH SETIAP WARGA WAJIB MEMATUHI PERATURAN YANG ADA DI KOTA SecretSociety.ID?",
        propositionA : "setiap warga wajib untuk mematuhi seluruh peraturan yang ada",
        propositionB : "setiap warga tidak wajib untuk mematuhi seluruh peraturan yang ada",
        propositionC : "setiap warga boleh berbuat semaunya disini",
        propositionD : "setiap warga boleh melakukan apapun yang mereka mau",
        reponse : "A"},
    {   question : "APA ITU OOC?",
        propositionA : "on on cantik",
        propositionB : "singkatan yang terdiri dari 3 huruf berawalan O O dan C",
        propositionC : "Tidak Tahu",
        propositionD : "Out Of Character",
        reponse : "D"},
    {   question : "APA ITU IC?",
        propositionA : "ini ciapa?",
        propositionB : "singkatan yang terdiri dari dua huruf berawal I dan C",
        propositionC : "lupa saya",
        propositionD : "in-character",
        reponse : "D"},
]

